site_name: Z2H
copyright: <br>
  <hr>
  Copyright 2023 ©️ <a href="https://volkan.io/">Volkan Özçelik</a> — 
  <a 
  href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en">CC-A-NC-SA 4.0</a>
theme:
  name: terminal
  custom_dir: overrides
  features:
    - navigation.side.hide